markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

site_name: Evobench

theme: 
  name: material

nav:
  - Home: index.md
  
